# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/EasyAuth.ContainerApp /source/EasyAuth.ContainerApp
COPY ./src/EasyAuth.Components /source/EasyAuth.Components

WORKDIR /source/EasyAuth.ContainerApp

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "EasyAuth.ContainerApp.dll"]